# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Movie DB' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'SwiftyJSON'
    pod 'Alamofire', '~> 4.0'
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'SDWebImage', '~>3.8'      

  target 'Movie DBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Movie DBUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
